In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv('stock_list.csv')
df

,SecuritiesCode,EffectiveDate,Name,Section/Products,NewMarketSegment,33SectorCode,33SectorName,17SectorCode,17SectorName,NewIndexSeriesSizeCode,NewIndexSeriesSize,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,20211230,"KYOKUYO CO.,LTD.",First Section (Domestic),Prime Market,50,"Fishery, Agriculture and Forestry",1,FOODS,7,TOPIX Small 2,20211230.0,3080.0,1.092828e+07,3.365911e+10,True
1,1305,20211230,Daiwa ETF-TOPIX,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2097.0,3.634636e+09,7.621831e+12,False
2,1306,20211230,NEXT FUNDS TOPIX Exchange Traded Fund,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2073.5,7.917718e+09,1.641739e+13,False
3,1308,20211230,Nikko Exchange Traded Index Fund TOPIX,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2053.0,3.736943e+09,7.671945e+12,False
4,1309,20211230,NEXT FUNDS ChinaAMC SSE50 Index Exchange Trade...,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,44280.0,7.263200e+04,3.216145e+09,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4412,9994,20211230,YAMAYA CORPORATION,First Section (Domestic),Standard Market,6100,Retail Trade,14,RETAIL TRADE,7,TOPIX Small 2,20211230.0,2447.0,1.084787e+07,2.654474e+10,True
4413,9995,20211230,"GLOSEL Co.,Ltd.",First Section (Domestic),Prime Market,6050,Wholesale Trade,13,COMMERCIAL & WHOLESALE TRADE,7,TOPIX Small 2,20211230.0,410.0,2.642680e+07,1.083499e+10,False
4414,9996,20211230,"Satoh&Co.,Ltd.",JASDAQ(Standard / Domestic),Standard Market,6050,Wholesale Trade,13,COMMERCIAL & WHOLESALE TRADE,-,-,20211230.0,1488.0,9.152640e+06,1.361913e+10,False
4415,9997,20211230,"BELLUNA CO.,LTD.",First Section (Domestic),Prime Market,6100,Retail Trade,14,RETAIL TRADE,6,TOPIX Small 1,20211230.0,709.0,9.724447e+07,6.894633e+10,True
4416,25935,20211230,"ITO EN,LTD.(shares of preferred stock)",First Section (Domestic),NaN,3050,Foods,1,FOODS,-,-,20211230.0,1934.0,3.424696e+07,6.623362e+10,False

In [91]:
df.drop(['EffectiveDate'],axis=1,inplace=True)
df.head()

,SecuritiesCode,Name,Section/Products,NewMarketSegment,33SectorCode,33SectorName,17SectorCode,17SectorName,NewIndexSeriesSizeCode,NewIndexSeriesSize,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,"KYOKUYO CO.,LTD.",First Section (Domestic),Prime Market,50,"Fishery, Agriculture and Forestry",1,FOODS,7,TOPIX Small 2,20211230.0,3080.0,1.092828e+07,3.365911e+10,True
1,1305,Daiwa ETF-TOPIX,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2097.0,3.634636e+09,7.621831e+12,False
2,1306,NEXT FUNDS TOPIX Exchange Traded Fund,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2073.5,7.917718e+09,1.641739e+13,False
3,1308,Nikko Exchange Traded Index Fund TOPIX,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2053.0,3.736943e+09,7.671945e+12,False
4,1309,NEXT FUNDS ChinaAMC SSE50 Index Exchange Trade...,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,44280.0,7.263200e+04,3.216145e+09,False

In [92]:
df.isnull().sum()

SecuritiesCode              0
Name                        0
Section/Products            0
NewMarketSegment          645
33SectorCode                0
33SectorName                0
17SectorCode                0
17SectorName                0
NewIndexSeriesSizeCode      0
NewIndexSeriesSize          0
TradeDate                 296
Close                     296
IssuedShares              296
MarketCapitalization      296
Universe0                   0
dtype: int64

In [93]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Universe0']=le.fit_transform(df['Universe0'])
df.head()

,SecuritiesCode,Name,Section/Products,NewMarketSegment,33SectorCode,33SectorName,17SectorCode,17SectorName,NewIndexSeriesSizeCode,NewIndexSeriesSize,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,"KYOKUYO CO.,LTD.",First Section (Domestic),Prime Market,50,"Fishery, Agriculture and Forestry",1,FOODS,7,TOPIX Small 2,20211230.0,3080.0,1.092828e+07,3.365911e+10,1
1,1305,Daiwa ETF-TOPIX,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2097.0,3.634636e+09,7.621831e+12,0
2,1306,NEXT FUNDS TOPIX Exchange Traded Fund,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2073.5,7.917718e+09,1.641739e+13,0
3,1308,Nikko Exchange Traded Index Fund TOPIX,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2053.0,3.736943e+09,7.671945e+12,0
4,1309,NEXT FUNDS ChinaAMC SSE50 Index Exchange Trade...,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,44280.0,7.263200e+04,3.216145e+09,0

In [94]:
df.drop(['Name'],axis=1,inplace=True)
df.head()

,SecuritiesCode,Section/Products,NewMarketSegment,33SectorCode,33SectorName,17SectorCode,17SectorName,NewIndexSeriesSizeCode,NewIndexSeriesSize,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,First Section (Domestic),Prime Market,50,"Fishery, Agriculture and Forestry",1,FOODS,7,TOPIX Small 2,20211230.0,3080.0,1.092828e+07,3.365911e+10,1
1,1305,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2097.0,3.634636e+09,7.621831e+12,0
2,1306,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2073.5,7.917718e+09,1.641739e+13,0
3,1308,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,2053.0,3.736943e+09,7.671945e+12,0
4,1309,ETFs/ ETNs,NaN,-,-,-,-,-,-,20211230.0,44280.0,7.263200e+04,3.216145e+09,0

In [95]:
df.drop(['33SectorName'],axis=1,inplace=True)

df.head()

,SecuritiesCode,Section/Products,NewMarketSegment,33SectorCode,17SectorCode,17SectorName,NewIndexSeriesSizeCode,NewIndexSeriesSize,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,First Section (Domestic),Prime Market,50,1,FOODS,7,TOPIX Small 2,20211230.0,3080.0,1.092828e+07,3.365911e+10,1
1,1305,ETFs/ ETNs,NaN,-,-,-,-,-,20211230.0,2097.0,3.634636e+09,7.621831e+12,0
2,1306,ETFs/ ETNs,NaN,-,-,-,-,-,20211230.0,2073.5,7.917718e+09,1.641739e+13,0
3,1308,ETFs/ ETNs,NaN,-,-,-,-,-,20211230.0,2053.0,3.736943e+09,7.671945e+12,0
4,1309,ETFs/ ETNs,NaN,-,-,-,-,-,20211230.0,44280.0,7.263200e+04,3.216145e+09,0

In [96]:
df.drop(['17SectorName'],axis=1,inplace=True)
df.head()

,SecuritiesCode,Section/Products,NewMarketSegment,33SectorCode,17SectorCode,NewIndexSeriesSizeCode,NewIndexSeriesSize,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,First Section (Domestic),Prime Market,50,1,7,TOPIX Small 2,20211230.0,3080.0,1.092828e+07,3.365911e+10,1
1,1305,ETFs/ ETNs,NaN,-,-,-,-,20211230.0,2097.0,3.634636e+09,7.621831e+12,0
2,1306,ETFs/ ETNs,NaN,-,-,-,-,20211230.0,2073.5,7.917718e+09,1.641739e+13,0
3,1308,ETFs/ ETNs,NaN,-,-,-,-,20211230.0,2053.0,3.736943e+09,7.671945e+12,0
4,1309,ETFs/ ETNs,NaN,-,-,-,-,20211230.0,44280.0,7.263200e+04,3.216145e+09,0

In [97]:
df.drop(['NewIndexSeriesSize'],axis=1,inplace=True)
df.head()

,SecuritiesCode,Section/Products,NewMarketSegment,33SectorCode,17SectorCode,NewIndexSeriesSizeCode,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,First Section (Domestic),Prime Market,50,1,7,20211230.0,3080.0,1.092828e+07,3.365911e+10,1
1,1305,ETFs/ ETNs,NaN,-,-,-,20211230.0,2097.0,3.634636e+09,7.621831e+12,0
2,1306,ETFs/ ETNs,NaN,-,-,-,20211230.0,2073.5,7.917718e+09,1.641739e+13,0
3,1308,ETFs/ ETNs,NaN,-,-,-,20211230.0,2053.0,3.736943e+09,7.671945e+12,0
4,1309,ETFs/ ETNs,NaN,-,-,-,20211230.0,44280.0,7.263200e+04,3.216145e+09,0

In [98]:

df['TradeDate'] = pd.to_datetime(
	df['TradeDate'].astype(str).str.replace(r'\.0$', '', regex=True),
	format='%Y%m%d'
)
df

,SecuritiesCode,Section/Products,NewMarketSegment,33SectorCode,17SectorCode,NewIndexSeriesSizeCode,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0
0,1301,First Section (Domestic),Prime Market,50,1,7,2021-12-30,3080.0,1.092828e+07,3.365911e+10,1
1,1305,ETFs/ ETNs,NaN,-,-,-,2021-12-30,2097.0,3.634636e+09,7.621831e+12,0
2,1306,ETFs/ ETNs,NaN,-,-,-,2021-12-30,2073.5,7.917718e+09,1.641739e+13,0
3,1308,ETFs/ ETNs,NaN,-,-,-,2021-12-30,2053.0,3.736943e+09,7.671945e+12,0
4,1309,ETFs/ ETNs,NaN,-,-,-,2021-12-30,44280.0,7.263200e+04,3.216145e+09,0
...,...,...,...,...,...,...,...,...,...,...,...
4412,9994,First Section (Domestic),Standard Market,6100,14,7,2021-12-30,2447.0,1.084787e+07,2.654474e+10,1
4413,9995,First Section (Domestic),Prime Market,6050,13,7,2021-12-30,410.0,2.642680e+07,1.083499e+10,0
4414,9996,JASDAQ(Standard / Domestic),Standard Market,6050,13,-,2021-12-30,1488.0,9.152640e+06,1.361913e+10,0
4415,9997,First Section (Domestic),Prime Market,6100,14,6,2021-12-30,709.0,9.724447e+07,6.894633e+10,1
4416,25935,First Section (Domestic),NaN,3050,1,-,2021-12-30,1934.0,3.424696e+07,6.623362e+10,0

In [99]:
df['Year'] = df['TradeDate'].dt.year
df['Month'] = df['TradeDate'].dt.month
df['Day'] = df['TradeDate'].dt.day

In [100]:

df['DayOfWeek'] = df['TradeDate'].dt.dayofweek   
df['Quarter'] = df['TradeDate'].dt.quarter
df['IsMonthStart'] = df['TradeDate'].dt.is_month_start.astype(int)
df['IsMonthEnd'] = df['TradeDate'].dt.is_month_end.astype(int)
df['IsQuarterEnd'] = df['TradeDate'].dt.is_quarter_end.astype(int)
df['IsYearEnd'] = df['TradeDate'].dt.is_year_end.astype(int)
df.head()

,SecuritiesCode,Section/Products,NewMarketSegment,33SectorCode,17SectorCode,NewIndexSeriesSizeCode,TradeDate,Close,IssuedShares,MarketCapitalization,Universe0,Year,Month,Day,DayOfWeek,Quarter,IsMonthStart,IsMonthEnd,IsQuarterEnd,IsYearEnd
0,1301,First Section (Domestic),Prime Market,50,1,7,2021-12-30,3080.0,1.092828e+07,3.365911e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
1,1305,ETFs/ ETNs,NaN,-,-,-,2021-12-30,2097.0,3.634636e+09,7.621831e+12,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
2,1306,ETFs/ ETNs,NaN,-,-,-,2021-12-30,2073.5,7.917718e+09,1.641739e+13,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
3,1308,ETFs/ ETNs,NaN,-,-,-,2021-12-30,2053.0,3.736943e+09,7.671945e+12,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
4,1309,ETFs/ ETNs,NaN,-,-,-,2021-12-30,44280.0,7.263200e+04,3.216145e+09,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0

In [101]:
df.drop(['TradeDate'],axis=1,inplace =True)

In [102]:
df.dropna(inplace=True)
df

,SecuritiesCode,Section/Products,NewMarketSegment,33SectorCode,17SectorCode,NewIndexSeriesSizeCode,Close,IssuedShares,MarketCapitalization,Universe0,Year,Month,Day,DayOfWeek,Quarter,IsMonthStart,IsMonthEnd,IsQuarterEnd,IsYearEnd
0,1301,First Section (Domestic),Prime Market,50,1,7,3080.0,10928283.0,3.365911e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
19,1332,First Section (Domestic),Prime Market,50,1,4,543.0,312430277.0,1.696496e+11,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
20,1333,First Section (Domestic),Prime Market,50,1,4,2405.0,52656910.0,1.266399e+11,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
26,1352,First Section (Domestic),Standard Market,6050,13,7,856.0,8379000.0,7.172424e+09,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
37,1375,First Section (Domestic),Prime Market,50,1,6,1196.0,39910700.0,4.773320e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4411,9993,First Section (Domestic),Standard Market,6100,14,7,1626.0,10960825.0,1.782230e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
4412,9994,First Section (Domestic),Standard Market,6100,14,7,2447.0,10847870.0,2.654474e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
4413,9995,First Section (Domestic),Prime Market,6050,13,7,410.0,26426800.0,1.083499e+10,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
4414,9996,JASDAQ(Standard / Domestic),Standard Market,6050,13,-,1488.0,9152640.0,1.361913e+10,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
4415,9997,First Section (Domestic),Prime Market,6100,14,6,709.0,97244472.0,6.894633e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0

In [103]:
df['NewMarketSegment'].unique()

array(['Prime Market', 'Standard Market', 'Growth Market',
       'Prime Market (Foreign Stock)', 'Standard Market (Foreign Stock)',
       'Growth Market (Foreign Stock)'], dtype=object)

In [104]:
from sklearn.preprocessing import OneHotEncoder
oh1=OneHotEncoder()
oh2=OneHotEncoder()
oh3=OneHotEncoder()
oh4=OneHotEncoder()
oh5=OneHotEncoder()
market=oh1.fit_transform(df[['NewMarketSegment']]).toarray()
market_df=pd.DataFrame(market,columns=oh1.get_feature_names_out(['NewMarketSegment']))
market_df.head()

,NewMarketSegment_Growth Market,NewMarketSegment_Growth Market (Foreign Stock),NewMarketSegment_Prime Market,NewMarketSegment_Prime Market (Foreign Stock),NewMarketSegment_Standard Market,NewMarketSegment_Standard Market (Foreign Stock)
0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0

In [105]:
products_1=oh2.fit_transform(df[['Section/Products']]).toarray()
products_df_1=pd.DataFrame(products_1,columns=oh2.get_feature_names_out(['Section/Products']))
products_df_1.head()

,Section/Products_First Section (Domestic),Section/Products_First Section (Foreign),Section/Products_JASDAQ(Growth/Domestic),Section/Products_JASDAQ(Standard / Domestic),Section/Products_JASDAQ(Standard / Foreign),Section/Products_Mothers (Domestic),Section/Products_Mothers (Foreign),Section/Products_Second Section(Domestic),Section/Products_Second Section(Foreign)
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [106]:
code33=oh3.fit_transform(df[['33SectorCode']]).toarray()
code33_df=pd.DataFrame(code33,columns=oh3.get_feature_names_out(['33SectorCode']))
code33_df.head()

,33SectorCode_1050,33SectorCode_2050,33SectorCode_3050,33SectorCode_3100,33SectorCode_3150,33SectorCode_3200,33SectorCode_3250,33SectorCode_3300,33SectorCode_3350,33SectorCode_3400,...,33SectorCode_5200,33SectorCode_5250,33SectorCode_6050,33SectorCode_6100,33SectorCode_7050,33SectorCode_7100,33SectorCode_7150,33SectorCode_7200,33SectorCode_8050,33SectorCode_9050
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [107]:
code17=oh4.fit_transform(df[['17SectorCode']]).toarray()
code17_df=pd.DataFrame(code17,columns=oh4.get_feature_names_out(['17SectorCode']))
code17_df.head()

,17SectorCode_1,17SectorCode_10,17SectorCode_11,17SectorCode_12,17SectorCode_13,17SectorCode_14,17SectorCode_15,17SectorCode_16,17SectorCode_17,17SectorCode_2,17SectorCode_3,17SectorCode_4,17SectorCode_5,17SectorCode_6,17SectorCode_7,17SectorCode_8,17SectorCode_9
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [108]:
code_new_index=oh5.fit_transform(df[['NewIndexSeriesSizeCode']]).toarray()
code_new_index_df=pd.DataFrame(code_new_index,columns=oh5.get_feature_names_out(['NewIndexSeriesSizeCode']))
code_new_index_df.head()

,NewIndexSeriesSizeCode_-,NewIndexSeriesSizeCode_1,NewIndexSeriesSizeCode_2,NewIndexSeriesSizeCode_4,NewIndexSeriesSizeCode_6,NewIndexSeriesSizeCode_7
0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,1.0,0.0

In [109]:
df = df.drop(columns=['SecuritiesCode'])
df.head()

,Section/Products,NewMarketSegment,33SectorCode,17SectorCode,NewIndexSeriesSizeCode,Close,IssuedShares,MarketCapitalization,Universe0,Year,Month,Day,DayOfWeek,Quarter,IsMonthStart,IsMonthEnd,IsQuarterEnd,IsYearEnd
0,First Section (Domestic),Prime Market,50,1,7,3080.0,10928283.0,3.365911e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
19,First Section (Domestic),Prime Market,50,1,4,543.0,312430277.0,1.696496e+11,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
20,First Section (Domestic),Prime Market,50,1,4,2405.0,52656910.0,1.266399e+11,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
26,First Section (Domestic),Standard Market,6050,13,7,856.0,8379000.0,7.172424e+09,0,2021.0,12.0,30.0,3.0,4.0,0,0,0,0
37,First Section (Domestic),Prime Market,50,1,6,1196.0,39910700.0,4.773320e+10,1,2021.0,12.0,30.0,3.0,4.0,0,0,0,0

In [110]:
df=pd.concat([df,market_df,products_df_1,code33_df,code17_df,code_new_index_df],axis=1)
df.drop(['NewMarketSegment','Section/Products','33SectorCode','17SectorCode','NewIndexSeriesSizeCode'],axis=1,inplace=True)
df.head()

,Close,IssuedShares,MarketCapitalization,Universe0,Year,Month,Day,DayOfWeek,Quarter,IsMonthStart,...,17SectorCode_6,17SectorCode_7,17SectorCode_8,17SectorCode_9,NewIndexSeriesSizeCode_-,NewIndexSeriesSizeCode_1,NewIndexSeriesSizeCode_2,NewIndexSeriesSizeCode_4,NewIndexSeriesSizeCode_6,NewIndexSeriesSizeCode_7
0,3080.0,10928283.0,3.365911e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,543.0,312430277.0,1.696496e+11,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
20,2405.0,52656910.0,1.266399e+11,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
26,856.0,8379000.0,7.172424e+09,0.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
37,1196.0,39910700.0,4.773320e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [111]:
import pickle 
pickle.dump(oh1, open('onehot_encoder.pkl', 'wb'))
pickle.dump(oh2, open('onehot_encoder_2.pkl', 'wb'))
pickle.dump(oh3, open('onehot_encoder_3.pkl', 'wb'))
pickle.dump(oh4, open('onehot_encoder_4.pkl', 'wb'))
pickle.dump(oh5, open('onehot_encoder_5.pkl', 'wb'))

In [112]:
df.dropna(inplace=True)

In [113]:
df.isnull().sum()

Close                       0
IssuedShares                0
MarketCapitalization        0
Universe0                   0
Year                        0
                           ..
NewIndexSeriesSizeCode_1    0
NewIndexSeriesSizeCode_2    0
NewIndexSeriesSizeCode_4    0
NewIndexSeriesSizeCode_6    0
NewIndexSeriesSizeCode_7    0
Length: 84, dtype: int64

In [114]:
df

,Close,IssuedShares,MarketCapitalization,Universe0,Year,Month,Day,DayOfWeek,Quarter,IsMonthStart,...,17SectorCode_6,17SectorCode_7,17SectorCode_8,17SectorCode_9,NewIndexSeriesSizeCode_-,NewIndexSeriesSizeCode_1,NewIndexSeriesSizeCode_2,NewIndexSeriesSizeCode_4,NewIndexSeriesSizeCode_6,NewIndexSeriesSizeCode_7
0,3080.0,10928283.0,3.365911e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,543.0,312430277.0,1.696496e+11,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
20,2405.0,52656910.0,1.266399e+11,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
26,856.0,8379000.0,7.172424e+09,0.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
37,1196.0,39910700.0,4.773320e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3756,860.0,32783000.0,2.819338e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3757,1933.0,41831897.0,8.086106e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3758,1404.0,24144669.0,3.389912e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3760,1592.0,11641318.0,1.853298e+10,1.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3761,1781.0,5444400.0,9.696476e+09,0.0,2021.0,12.0,30.0,3.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [115]:
from sklearn.model_selection import train_test_split
X=df.drop(['Close'],axis=1)
y=df['Close']
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [116]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler2=StandardScaler()
x_train=scaler.fit_transform(x_train)
y_train=scaler2.fit_transform(y_train.values.reshape(-1,1))
x_test=scaler.transform(x_test)
y_test=scaler2.transform(y_test.values.reshape(-1,1))

In [117]:
pickle.dump(scaler, open('scaler.pkl', 'wb'))
pickle.dump(scaler2, open('scaler_y.pkl', 'wb'))

In [118]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [119]:
model=Sequential(
  [
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(64,activation='relu'),
    Dense(1)
  ]
)

c:\Users\amiya\.conda\envs\DL-new\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [120]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 64)             │         5,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,601 (37.50 KB)

 Trainable params: 9,601 (37.50 KB)

 Non-trainable params: 0 (0.00 B)

In [121]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
loss=tf.keras.losses.MeanSquaredError()
model.compile(optimizer=opt,loss=loss,metrics=['mae'])
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%M%d-%H%M%S")
TensorBoard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)
EarlyStopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)
history=model.fit(
  x_train,y_train,
  validation_data=(x_test,y_test),
  epochs=100,
  batch_size=32,
  verbose=1,
  callbacks=[EarlyStopping_callback,TensorBoard_callback]

)

Epoch 1/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.9759 - mae: 0.4393 - val_loss: 0.5395 - val_mae: 0.3639
Epoch 2/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8076 - mae: 0.3852 - val_loss: 0.4814 - val_mae: 0.3475
Epoch 3/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7204 - mae: 0.3768 - val_loss: 0.4680 - val_mae: 0.3348
Epoch 4/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6665 - mae: 0.3729 - val_loss: 0.4533 - val_mae: 0.3321
Epoch 5/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6082 - mae: 0.3597 - val_loss: 0.4418 - val_mae: 0.3276
Epoch 6/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5557 - mae: 0.3557 - val_loss: 0.4081 - val_mae: 0.3156
Epoch 7/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4944 - mae: 0.3386 - val_loss: 0.4053 - val_mae: 0.3083
Epoch 8/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4656 - mae: 0.3310 - val_loss: 0.4026 - val_mae: 0.3136
Epoch 9/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4435 - mae: 0.3302 - val_loss: 0.4128 - val_mae: 0.3172
Epoch 10/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4286 - mae: 0.3308 - val_loss: 0.3946 - val_mae: 0.3125
Epoch 11/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3959 - mae: 0.3194 - val_loss: 0.3848 - val_mae: 0.3138
Epoch 12/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3883 - mae: 0.3245 - val_loss: 0.4060 - val_mae: 0.3052
Epoch 13/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3820 - mae: 0.3190 - val_loss: 0.4035 - val_mae: 0.3281
Epoch 14/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3753 - mae: 0.3173 - val_loss: 0.4238 - val_mae: 0.3289
Epoch 15/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3567 - mae: 0.3093 - val_loss: 0.3902 - val_mae: 0.3250
Epoch 16/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3456 - mae: 0.3131 - val_loss: 0.3952 - val_mae: 0.3218
Epoch 17/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3405 - mae: 0.3063 - val_loss: 0.3888 - val_mae: 0.3177
Epoch 18/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3354 - mae: 0.3137 - val_loss: 0.3870 - val_mae: 0.3074
Epoch 19/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3174 - mae: 0.2917 - val_loss: 0.4399 - val_mae: 0.3282
Epoch 20/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.3187 - mae: 0.3063 - val_loss: 0.3720 - val_mae: 0.2969
Epoch 21/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3019 - mae: 0.2947 - val_loss: 0.3881 - val_mae: 0.3010
Epoch 22/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2938 - mae: 0.2929 - val_loss: 0.3530 - val_mae: 0.2978
Epoch 23/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2843 - mae: 0.2905 - val_loss: 0.3650 - val_mae: 0.2920
Epoch 24/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2844 - mae: 0.2890 - val_loss: 0.3612 - val_mae: 0.2780
Epoch 25/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2660 - mae: 0.2774 - val_loss: 0.3825 - val_mae: 0.3126
Epoch 26/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2750 - mae: 0.2911 - val_loss: 0.3565 - val_mae: 0.3150
Epoch 27/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2689 - mae: 0.2835 - val_loss: 0.3434 - val_mae: 0.2888
Epoch 28/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2768 - mae: 0.2851 - val_loss: 0.3714 - val_mae: 0.3329
Epoch 29/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2543 - mae: 0.2741 - val_loss: 0.3831 - val_mae: 0.3435
Epoch 30/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2672 - mae: 0.2750 - val_loss: 0.3721 - val_mae: 0.3068
Epoch 31/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2508 - mae: 0.2742 - val_loss: 0.3559 - val_mae: 0.3003
Epoch 32/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2456 - mae: 0.2718 - val_loss: 0.3448 - val_mae: 0.2731
Epoch 33/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2391 - mae: 0.2571 - val_loss: 0.3563 - val_mae: 0.2894
Epoch 34/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2427 - mae: 0.2671 - val_loss: 0.3371 - val_mae: 0.3028
Epoch 35/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2399 - mae: 0.2672 - val_loss: 0.3391 - val_mae: 0.2752
Epoch 36/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2305 - mae: 0.2596 - val_loss: 0.3516 - val_mae: 0.2953
Epoch 37/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2302 - mae: 0.2564 - val_loss: 0.3306 - val_mae: 0.2926
Epoch 38/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2303 - mae: 0.2614 - val_loss: 0.3256 - val_mae: 0.2758
Epoch 39/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2235 - mae: 0.2488 - val_loss: 0.3105 - val_mae: 0.2665
Epoch 40/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2178 - mae: 0.2510 - val_loss: 0.3670 - val_mae: 0.3362
Epoch 41/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2231 - mae: 0.2565 - val_loss: 0.3138 - val_mae: 0.2683
Epoch 42/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2215 - mae: 0.2469 - val_loss: 0.3155 - val_mae: 0.2879
Epoch 43/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2230 - mae: 0.2536 - val_loss: 0.3100 - val_mae: 0.2645
Epoch 44/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2131 - mae: 0.2469 - val_loss: 0.3170 - val_mae: 0.2943
Epoch 45/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2123 - mae: 0.2503 - val_loss: 0.3219 - val_mae: 0.2912
Epoch 46/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2100 - mae: 0.2443 - val_loss: 0.3195 - val_mae: 0.2762
Epoch 47/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2036 - mae: 0.2421 - val_loss: 0.3192 - val_mae: 0.2973
Epoch 48/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2055 - mae: 0.2457 - val_loss: 0.3182 - val_mae: 0.2993
Epoch 49/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1970 - mae: 0.2366 - val_loss: 0.3164 - val_mae: 0.2901
Epoch 50/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2058 - mae: 0.2469 - val_loss: 0.3054 - val_mae: 0.2720
Epoch 51/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1930 - mae: 0.2331 - val_loss: 0.2839 - val_mae: 0.2698
Epoch 52/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1964 - mae: 0.2335 - val_loss: 0.2961 - val_mae: 0.2737
Epoch 53/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1984 - mae: 0.2378 - val_loss: 0.2915 - val_mae: 0.2761
Epoch 54/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2041 - mae: 0.2407 - val_loss: 0.2858 - val_mae: 0.2643
Epoch 55/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1895 - mae: 0.2329 - val_loss: 0.3018 - val_mae: 0.2766
Epoch 56/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1889 - mae: 0.2302 - val_loss: 0.3040 - val_mae: 0.3080
Epoch 57/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1892 - mae: 0.2370 - val_loss: 0.3055 - val_mae: 0.2774
Epoch 58/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1943 - mae: 0.2314 - val_loss: 0.2858 - val_mae: 0.2666
Epoch 59/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2039 - mae: 0.2433 - val_loss: 0.3214 - val_mae: 0.3044
Epoch 60/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1901 - mae: 0.2351 - val_loss: 0.2831 - val_mae: 0.2589
Epoch 61/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1893 - mae: 0.2299 - val_loss: 0.2721 - val_mae: 0.2756
Epoch 62/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1868 - mae: 0.2323 - val_loss: 0.3012 - val_mae: 0.2894
Epoch 63/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1896 - mae: 0.2319 - val_loss: 0.2839 - val_mae: 0.2639
Epoch 64/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1782 - mae: 0.2265 - val_loss: 0.2777 - val_mae: 0.2703
Epoch 65/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1842 - mae: 0.2371 - val_loss: 0.2820 - val_mae: 0.2659
Epoch 66/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1761 - mae: 0.2233 - val_loss: 0.2835 - val_mae: 0.2813
Epoch 67/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1745 - mae: 0.2177 - val_loss: 0.3063 - val_mae: 0.3057
Epoch 68/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1765 - mae: 0.2212 - val_loss: 0.2552 - val_mae: 0.2647
Epoch 69/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1782 - mae: 0.2224 - val_loss: 0.2655 - val_mae: 0.2727
Epoch 70/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1695 - mae: 0.2148 - val_loss: 0.3092 - val_mae: 0.3325
Epoch 71/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1784 - mae: 0.2241 - val_loss: 0.2460 - val_mae: 0.2499
Epoch 72/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1812 - mae: 0.2218 - val_loss: 0.2685 - val_mae: 0.2543
Epoch 73/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1752 - mae: 0.2214 - val_loss: 0.2509 - val_mae: 0.2484
Epoch 74/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1685 - mae: 0.2096 - val_loss: 0.2535 - val_mae: 0.2597
Epoch 75/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1709 - mae: 0.2234 - val_loss: 0.2322 - val_mae: 0.2396
Epoch 76/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1800 - mae: 0.2252 - val_loss: 0.2608 - val_mae: 0.2549
Epoch 77/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1751 - mae: 0.2212 - val_loss: 0.2721 - val_mae: 0.2605
Epoch 78/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1782 - mae: 0.2228 - val_loss: 0.2512 - val_mae: 0.2570
Epoch 79/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1640 - mae: 0.2075 - val_loss: 0.2433 - val_mae: 0.2716
Epoch 80/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1581 - mae: 0.2160 - val_loss: 0.2298 - val_mae: 0.2482
Epoch 81/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1720 - mae: 0.2189 - val_loss: 0.2389 - val_mae: 0.2418
Epoch 82/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1585 - mae: 0.2069 - val_loss: 0.2506 - val_mae: 0.2680
Epoch 83/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1697 - mae: 0.2106 - val_loss: 0.2370 - val_mae: 0.2371
Epoch 84/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1579 - mae: 0.2102 - val_loss: 0.2429 - val_mae: 0.2441
Epoch 85/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1649 - mae: 0.2066 - val_loss: 0.2312 - val_mae: 0.2360
Epoch 86/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1642 - mae: 0.2086 - val_loss: 0.2395 - val_mae: 0.2506
Epoch 87/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1614 - mae: 0.2070 - val_loss: 0.2403 - val_mae: 0.2532
Epoch 88/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1561 - mae: 0.2053 - val_loss: 0.2546 - val_mae: 0.2577
Epoch 89/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1580 - mae: 0.2101 - val_loss: 0.2223 - val_mae: 0.2399
Epoch 90/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1518 - mae: 0.2006 - val_loss: 0.2659 - val_mae: 0.2725
Epoch 91/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1630 - mae: 0.2061 - val_loss: 0.2450 - val_mae: 0.2504
Epoch 92/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1538 - mae: 0.1999 - val_loss: 0.2604 - val_mae: 0.2665
Epoch 93/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1604 - mae: 0.2105 - val_loss: 0.2503 - val_mae: 0.2436
Epoch 94/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1573 - mae: 0.2103 - val_loss: 0.2314 - val_mae: 0.2402
Epoch 95/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1526 - mae: 0.1960 - val_loss: 0.2508 - val_mae: 0.2771
Epoch 96/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1567 - mae: 0.2056 - val_loss: 0.2540 - val_mae: 0.2555
Epoch 97/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1603 - mae: 0.2024 - val_loss: 0.2254 - val_mae: 0.2403
Epoch 98/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1550 - mae: 0.2017 - val_loss: 0.2303 - val_mae: 0.2444
Epoch 99/100
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.1567 - mae: 0.2099 - val_loss: 0.2369 - val_mae: 0.2561

In [122]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 30116), started 16:00:03 ago. (Use '!kill 30116' to kill it.)

In [123]:
import keras_tuner as kt
from keras_tuner import RandomSearch,GridSearch,Hyperband
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout,InputLayer

In [124]:
def build_model(hp):
    model=Sequential()
    model.add(InputLayer(input_shape=(x_train.shape[1],)))
    
    n_hidden=hp.Int('n_hidden',min_value=1,max_value=5,step=1)
    n_neurons=hp.Choice('n_choice',values=[32,64,128,256])
    dropout_rate = hp.Choice('dropout_rate', values=[0.1, 0.2, 0.3, 0.4])
    activation = hp.Choice('activation', values=['relu', 'tanh'])
    for _ in range(n_hidden):
        model.add(Dense(n_neurons,activation=activation))
        model.add(Dropout(dropout_rate))
   
    model.add(Dense(1))
    learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),loss='mse',metrics=['mae'])
    return model

## hyperband

In [125]:
tuner=kt.Hyperband(
    build_model,                # our model-building function
    objective='val_mae',        # what to minimize
    max_epochs=50,              # max epochs per model
    factor=3,                   # how quickly we reduce bad models
    directory='hyperband_dir',  # folder to store results
    project_name='regression_tuning'  # subfolder name

)

tuner.search(
    x_train, y_train,
    epochs=50,
    validation_data=(x_test, y_test),
    batch_size=32,
    verbose=1
)

Reloading Tuner from hyperband_dir\regression_tuning\tuner0.json

In [126]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

In [127]:
print("Best Hyperparameters found:")
print(f"Number of Hidden Layers: {best_hps.get('n_hidden')}")
print(f"Neurons per Layer: {best_hps.get('n_choice')}")
print(f"Learning Rate: {best_hps.get('learning_rate')}")
print(f"Dropout Rate: {best_hps.get('dropout_rate')}")
print(f"Activation Function: {best_hps.get('activation')}")

Best Hyperparameters found:
Number of Hidden Layers: 3
Neurons per Layer: 64
Learning Rate: 0.001
Dropout Rate: 0.2
Activation Function: tanh

In [128]:
best_model = tuner.hypermodel.build(best_hps)

c:\Users\amiya\.conda\envs\DL-new\Lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

In [129]:
history = best_model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=50,
    batch_size=32,
    verbose=1
)

Epoch 1/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 1.0815 - mae: 0.5168 - val_loss: 0.5252 - val_mae: 0.3565
Epoch 2/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9408 - mae: 0.4955 - val_loss: 0.4843 - val_mae: 0.3166
Epoch 3/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8849 - mae: 0.4612 - val_loss: 0.4501 - val_mae: 0.3131
Epoch 4/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8670 - mae: 0.4628 - val_loss: 0.4437 - val_mae: 0.3230
Epoch 5/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.8572 - mae: 0.4509 - val_loss: 0.4285 - val_mae: 0.3254
Epoch 6/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.8321 - mae: 0.4460 - val_loss: 0.4042 - val_mae: 0.2967
Epoch 7/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7830 - mae: 0.4449 - val_loss: 0.3989 - val_mae: 0.3171
Epoch 8/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7632 - mae: 0.4366 - val_loss: 0.3874 - val_mae: 0.2978
Epoch 9/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7628 - mae: 0.4377 - val_loss: 0.3806 - val_mae: 0.2863
Epoch 10/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7656 - mae: 0.4240 - val_loss: 0.3710 - val_mae: 0.2861
Epoch 11/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7450 - mae: 0.4328 - val_loss: 0.3733 - val_mae: 0.2987
Epoch 12/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7389 - mae: 0.4124 - val_loss: 0.3823 - val_mae: 0.3516
Epoch 13/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7432 - mae: 0.4253 - val_loss: 0.3623 - val_mae: 0.2989
Epoch 14/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7040 - mae: 0.4123 - val_loss: 0.3566 - val_mae: 0.2920
Epoch 15/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6940 - mae: 0.4110 - val_loss: 0.3496 - val_mae: 0.2997
Epoch 16/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6980 - mae: 0.4142 - val_loss: 0.3483 - val_mae: 0.2800
Epoch 17/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6839 - mae: 0.4025 - val_loss: 0.3389 - val_mae: 0.2623
Epoch 18/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6810 - mae: 0.3980 - val_loss: 0.3334 - val_mae: 0.2844
Epoch 19/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6630 - mae: 0.3999 - val_loss: 0.3367 - val_mae: 0.2866
Epoch 20/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6571 - mae: 0.3992 - val_loss: 0.3209 - val_mae: 0.2789
Epoch 21/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6331 - mae: 0.3863 - val_loss: 0.3192 - val_mae: 0.2909
Epoch 22/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6280 - mae: 0.3993 - val_loss: 0.3218 - val_mae: 0.2801
Epoch 23/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6229 - mae: 0.3877 - val_loss: 0.3190 - val_mae: 0.2911
Epoch 24/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6255 - mae: 0.3923 - val_loss: 0.2979 - val_mae: 0.2570
Epoch 25/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5980 - mae: 0.3863 - val_loss: 0.2816 - val_mae: 0.2513
Epoch 26/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6031 - mae: 0.3923 - val_loss: 0.2784 - val_mae: 0.2631
Epoch 27/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6220 - mae: 0.4068 - val_loss: 0.3098 - val_mae: 0.2755
Epoch 28/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6072 - mae: 0.3780 - val_loss: 0.2835 - val_mae: 0.2545
Epoch 29/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5600 - mae: 0.3768 - val_loss: 0.2700 - val_mae: 0.2799
Epoch 30/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6045 - mae: 0.4053 - val_loss: 0.2797 - val_mae: 0.2550
Epoch 31/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5794 - mae: 0.3795 - val_loss: 0.2786 - val_mae: 0.2986
Epoch 32/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5905 - mae: 0.3832 - val_loss: 0.2576 - val_mae: 0.2542
Epoch 33/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5776 - mae: 0.3900 - val_loss: 0.2605 - val_mae: 0.2693
Epoch 34/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5675 - mae: 0.3810 - val_loss: 0.2568 - val_mae: 0.2730
Epoch 35/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5586 - mae: 0.3790 - val_loss: 0.2598 - val_mae: 0.2745
Epoch 36/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5460 - mae: 0.3745 - val_loss: 0.2278 - val_mae: 0.2518
Epoch 37/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5543 - mae: 0.3885 - val_loss: 0.2457 - val_mae: 0.2600
Epoch 38/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5514 - mae: 0.3762 - val_loss: 0.2269 - val_mae: 0.2546
Epoch 39/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5438 - mae: 0.3763 - val_loss: 0.2243 - val_mae: 0.2520
Epoch 40/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5620 - mae: 0.3973 - val_loss: 0.2253 - val_mae: 0.2338
Epoch 41/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5296 - mae: 0.3732 - val_loss: 0.2204 - val_mae: 0.2368
Epoch 42/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5687 - mae: 0.3913 - val_loss: 0.2484 - val_mae: 0.2542
Epoch 43/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5291 - mae: 0.3701 - val_loss: 0.2138 - val_mae: 0.2255
Epoch 44/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5146 - mae: 0.3885 - val_loss: 0.2326 - val_mae: 0.2619
Epoch 45/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5273 - mae: 0.3844 - val_loss: 0.2446 - val_mae: 0.2631
Epoch 46/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5465 - mae: 0.3830 - val_loss: 0.2297 - val_mae: 0.2653
Epoch 47/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5175 - mae: 0.3708 - val_loss: 0.2040 - val_mae: 0.2364
Epoch 48/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5144 - mae: 0.3809 - val_loss: 0.2356 - val_mae: 0.2707
Epoch 49/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4986 - mae: 0.3670 - val_loss: 0.2223 - val_mae: 0.2636
Epoch 50/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5190 - mae: 0.3770 - val_loss: 0.2075 - val_mae: 0.2473

In [130]:
test_loss, test_mae = best_model.evaluate(x_test, y_test, verbose=1)
print(f"\nTest MAE: {test_mae:.4f}")

20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2075 - mae: 0.2473

Test MAE: 0.2473

In [131]:
best_model.save('tuned_regression_model.keras')

In [132]:
feature_columns = X.columns.tolist()
with open('feature_columns.pkl', 'wb') as f:
    pickle.dump(feature_columns, f)

print(f"Saved {len(feature_columns)} feature columns")

Saved 83 feature columns